version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Backend/WebApi/Dockerfile
    container_name: music_backend
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
    networks:
      - music-network

  frontend:
    build:
      context: .
      dockerfile: Frontend/Dockerfile   
    container_name: music_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - music-network

networks:
  music-network:
    driver: bridge